version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
  open-pull-requests-limit: 20
  reviewers:
  - fmasa
  ignore:
  - dependency-name: sass-loader
    versions:
    - 10.1.1

